### ISSUE TITLE
pwm _set_period calculation

### ISSUE THREAD

**Issue by etrombly** [japaric/stm32f103xx-hal#23]
Just noticed a possible issue with _set_period that you wouldn't have noticed with just the default clock speed. If apb1 prescaler is anything other than 1 then the apb1 clock is multiplied by 2 before it's used by the timer. Here's how I ended up handling it, but it's evaluated at run time, so you would probably want a different solution. (took me a while to figure out the issue because it's like a single sentence in the documentation)

```rust
// PSC = (CLOCK / FREQ) / u16::MAX
// ARR = ((CLOCK / FREQ) + (PSC / 2)) / PSC

// if ppre1 is anything other than 1 the timer clock is multiplied by 2
let apb1_pre = rcc.cfgr.read().ppre1();
let apb1_mult = if apb1_pre == rcc::cfgr::Ppre1R::Div1 { 1 } else { 2 };

let speeds = frequency::ClockSpeeds::get(rcc);

// use 100Khz for default speed
let psc = ((speeds.apb1 * apb1_mult) / 100_000) as u16 / 0xFFFF + 1;

timer.psc.write(|w| w.psc().bits(psc));

let arr = ((speeds.apb1 * apb1_mult) / 100_000) as u16 + (psc / 2) / psc;
```

**Comment by japaric** [comment]
This is now properly handled thanks to the [`Clocks`] abstraction. Read this [blog post] for the basic idea about `Clocks` and *freezing* clock configuration.

[blog post]: http://blog.japaric.io/brave-new-io/
