### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by nallar** [japaric/stm32f103xx-hal#39]
There's no LICENSE file or license in Cargo.toml

**Comment by japaric** [comment]
> There's no LICENSE file

There's no file named LICENSE; instead there are two license files named LICENSE-MIT and LICENSE-APACHE. The approach used here is the same as the one used in the rust-lang/rust repo.

#40 adds license information to the crate metadata

**Comment by nallar** [comment]
> There's no file named LICENSE; instead there are two license files named LICENSE-MIT and LICENSE-APACHE. The approach used here is the same as the one used in the rust-lang/rust repo.

Oh. Not sure how I missed that.

> #40 adds license information to the crate metadata

Thanks!
